image: Visual Studio 2019

environment:
  matrix:
    - USE_MSVC: 1
      QTDIR: C:\Qt\5.15\msvc2017
      QTTOOLS: C:\Qt\Tools\QtCreator
    - USE_MINGW: 1
      QTDIR: C:\Qt\5.15\mingw73_32
      QTTOOLS: C:\Qt\Tools\mingw730_32

install:
  - DIR C:\Qt
  - DIR C:\Qt\Tools
  - DIR %QTDIR%\..
  - DIR %QTTOOLS%
  - set PATH=%QTDIR%\bin;%QTTOOLS%\bin;%PATH%
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"'

before_build:
  - qmake -config release Deling.pro

build_script:
  - if "%USE_MSVC%"=="1" jom
  - if "%USE_MINGW%"=="1" mingw32-make

after_build:
  - FOR /F %%i IN ('git describe --tags') DO SET GIT_TAG_OR_BRANCH=%%i
  - if "%USE_MSVC%"=="1" set DEPLOY_DIR="deling-%GIT_TAG_OR_BRANCH%-win32"
  - if "%USE_MINGW%"=="1" set DEPLOY_DIR="deling-%GIT_TAG_OR_BRANCH%-win32-xp"
  - echo "%DEPLOY_DIR%"
  - deploy.bat
  - MOVE *.qm deploy
  - DIR deploy
  - MOVE deploy "%DEPLOY_DIR%"
  - 7z a "%DEPLOY_DIR%.zip" "%DEPLOY_DIR%"

artifacts:
  - path: deling-*.zip

deploy:
  description: Description # Mandatory
  provider: GitHub
  auth_token:
    secure: hC7ZT9txiEAgKU9m2PzmUNe/eDYz1dNPT2DketUKF+8CwuDiXQgNzKSx33Rek2CF
  artifact: /deling-.*\.zip/
  on:
    appveyor_repo_tag: true # deploy on tag push only
